### ISSUE TITLE
Nested messages

### ISSUE THREAD

**Issue by marijamatijevi** [dutradda/asyncapi-python#5]
When trying to publish a message that has a nested structure or contains a list I get the following error. 

Traceback (most recent call last):
  File "publish.py", line 20, in <module>
    asyncio.run(publish())
  File "/app/vbuild/RHEL7-x86_64/python/3.8.0/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/app/vbuild/RHEL7-x86_64/python/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "publish.py", line 15, in publish
    await api.publish(channel_id, message)
  File "/repo/$USER/sched-db-service/env/lib/python3.8/site-packages/asyncapi/api.py", line 46, in publish
    message=self.parse_message(channel_id, message).decode(),
  File "/repo/$USER/sched-db-service/env/lib/python3.8/site-packages/asyncapi/api.py", line 185, in parse_message
    raise InvalidMessageError(message, type_)
asyncapi.exceptions.InvalidMessageError: ({}, <class 'specification.ExecutionCreatedPayload'>)
Unclosed AIOKafkaProducer
producer: <aiokafka.producer.producer.AIOKafkaProducer object at 0x7f3ced4e2f70>
Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7f3ced4e9640>

The structure looks something like this:

{
 key_A,
 key_B: [{
    key_C: [{key_D: value_D}]
  }]
}

**Comment by dutradda** [comment]
hello @marijamatijevi !

can you copy here the code you are executing?

**Comment by dutradda** [comment]
I think you should use the `await api.publish_json(channel_id, message)` method instead `await api.publish(channel_id, message)`.

the `api.publish` method expect a dataclass as argument.

**Comment by dutradda** [comment]
@marijamatijevi I have changed the `api.publish` method to call the `publish_json` if the message is a dict.

The version `0.14.1` has this change.

Thank you for the report!

**Comment by marijamatijevi** [comment]
Hi @dutradda ,

It's working fine now, thank you for your blazingly fast response!
